<template>
	<view class="chenyu_page" style="padding-left: 40rpx;">
<!-- 		<u-time-line>
			<u-time-line-item v-for="(item,index) in list" :key="index">
				<template v-slot:content>
					<view class="chenyu_card">
						<view class="u-order-title" :style="index==0?'color:#000000;font-size: 40rpx;':''">{{item.title}}</view>
						<view class="u-order-desc" :style="index==0?'color:#000000':''">
							<view class="text" v-for="(items,idx) in item.content" :key="idx">
								{{items}}
							</view>
						</view>
						<view class="u-order-time">{{item.time}}</view>
					</view>
				</template>
			</u-time-line-item>
		</u-time-line> -->
<!-- 		<chenyu-audioplay
			:audio_src="src"
			:audio_max="281"
			:audio_volume ="volume"
			:is_volume="true"
		/> -->
		<!-- <chenyu-textarea /> -->
		<chenyu-poster 
			ref="daochu" 
			:arr_img="post_arr" 
			:canvas_width="500"
			:canvas_height="800"
			@export_loading="export_loading"
			@export_success="export_success"
			:background_img="background_img" />
		<button type="default" @tap="chufa">触发</button>
		<chenyu-imagecache>
			<image class="" src="../we_service/trivia_books/static/logo.png" mode="scaleToFill"></image>
		</chenyu-imagecache>
	</view>
</template>

<script>
	const app = getApp()
	export default {
		//声明引用组件
		components:{},
		data() {
			return {
				list:[
					{
						title:"v1.0.0",
						content:[
							"1.初始版本，包含琐事便签功能",
							"2.本版本不包含用户信息体系，采用本地缓存技术来存储，删除本小程序后会随之消失"
						],
						time:"2020年6月25日"
					},
				],
				content:"",
				src:"",
				volume:0.8,
				background_img:"https://weiqing.chenyuwulu.top/data/timg.png",
				post_arr:[
					{
						type:"buffer",
						width:300,
						height:300,
						left:50,
						top:50,
						data:'iVBORw0KGgoAAAANSUhEUgAAAlgAAAJYCAIAAAAxBA+LAAAUWElEQVR42u3WgW0DMQwEwe+/6aSHwIj/uLMFGHmJ4uT5kSQp3OMIJEkglCQJhJIkgVCSJBBKkgRCSZJAKEkSCCVJAqEkSSCUJAmEkiSBUJIkEEqSBEJJkkAoSRIIJUkCoSRJIJQkCYSSJIFQkiQQSpIEQkmSQChJEgglSQKhJEkglCQJhJIkgVCSJBBKkgRCSZJAKEkSCCVJAqEkSSCUJAmEkiSBUJIkEEqSBEJJkkAoSRIIJUkCoSRJIJQkCYSSJIFQkiQQSpIEQkmSQChJEgglSQKhJEkglCQJhJIkgVCSBEJJkkAoSRIIJUkCoSRJIJQkCYSSJIFQkiQQSpIEQkmSQChJEgglSQKhJEkglCQJhJIkgVCSJBB++2P00d52/uvz5n3dnk/7AYQeqkEHIQhBaD+A0EMFIQhBCEL7AYQeKghBCEIQ2g8g9FBBCEIQgtB+ACEIQQhCEILQfgAhCEEIQhCC0H4AIQhBCEIQghCEIAQhCEHofYEQhCAEIQhB6H2BEIQgBCEIQeh9gRCEIAQhCEHofYEQhCAEIQhB6H2BEIQgBCEIQeh9gRCEIAQhCEHofYEQhCAEoUUDQu8LhCAEocXkfJyn7/X3Ox8Qukjn4zx9r7/f+YDQRTof5+l7/f3OB4Qu0vk4T9/r73c+IHSRzsd5+l735XxA6CKdj/P0ve7L+YDQRTof5+l73ZfzAaGLdD7O0/e6L+cDQhfpfJyn73VfzgeELtL5OE/f676cDwhdpPNxnr7XfTkfEBp05+M8fa/7cj4gNOjOx3n6XvflfEBo0J2P8/S95t/5gNCgOx/n6XvNv/MBoUF3Ps7T95p/5wPCz13k87LWz+dt81Br/fzth9vvF4QgBCEIQQhCEIIQhCAEIQhBCEIQGnQQghCEIAQhCA06CEEIQhCCEIQGHYQgBCEIQQhCgw5CEIIQhCAEoUEHIQhBCEIQgtCggxCEILQfQAhCgw5CEILQfgAhCA06CEEIQvsBhCA06CAEIQjtBxCC0KCDEIQgtB9ACEKDDkIQgtB+ACEIDToIQQhC+wGEIDToIBQI7QcQgtCg3zmfGvw1OO0HEILQoIMQhCC0H0AIQoNucYMQhPYDCEFo0C1uEILQfgAhCA26xQ1CENoPIAShQbe4QQhC+wGEIDToFjcIQWg/gBCEBt3iBiEI7QcQgtCggxCEILQfQAhCgw5CEILQfgAhCA06CEEIQvcFQhAadBCCEITuC4QgNOggBCEI3RcIQWjQQQhCELovEILQoIMQhCB0XyAEoUEHIQhB6L5ACEKD7nwuLPonlv0AQhAadBCCEIT2AwhBaNBBCEIQ2g8gBKFBByEIQWg/gBCEBh2EIASh/QBCEBp0EIIQhPYDCEFo0EEIQhDaDyAEoUEHIQhBaD+AEIQGHYQgBKH9AEIQGnQQghCE9gMIQWjQQQhCEJp/EILQoDsfEILQ/IMQhAbd+YAQhOYfhCA06M4HhCA0/yAEoUF3PiB0/uYfhCA06M4HhM7f/IMQhMWLXDwfi9L3lufNfgChi3Q+YPC9ILQfQOgiQQgG3wtC+wGELhKEYPC9ILQfQOgiQQgG32s/2A8gdJHgAYPvtR/sBxC6SPCAwffaD/YDCF0keMDge+0H+xOELhI8YPC99oP9CUIXCR4w+F77wf4EoYsEDxh8r/3gfEDoIsEDBt9rPzgfELpI8IDB99oPzgeELhI8YPC99oPzAaGLBA8YfK/94HxA6CItJjD4XvvB+YDw7xeprcXn9/3+f/6+QAhCWZR+H4QCIQgNukXp90EoEILQoFuUfh+EAiEIDbpF6fdBKBCC0KBblH4fhAIhCA26Ren3QSgQgtCgW5R+H4T2AwhBaNAtYr8PQvsBhCA06Bax3weh/QBCEBp0i9jvg9B+ACEIQej3/T4I7QcQghCEft/vg9B+ACEIQej3/T4I7QcQghCEft/vg9B+ACEIQej3/T4I7QcQSjcXa+0fQROrs7vIEQiEIAShQCiBEIQgFAglEIIQhAKhBEIQglAglEAIQhAKhBIIQQhCgVACIQhBKBBKIAShXSEQSiAEoQRCCYQglEAogRCEEgglEIJQAqEEQhBKIJRACEIJhBIIQSiB8PwiWF804PGPhXl2/t4vCEHoIYHQPDt/7xeEIPSQQGienb/3C0IQekggNM/O3/sFocXhIZl/8+z8QWgRWBwekvk3zyAEoUVgcXhI5t88gxCEFoHF4SGZf/MMQhBaBBaHh2T+zTMIQWgRWBwekvkHIQhBaBFYHB6S+QchCEFoEVgcHpL5ByEIQWgRWBwekvkHIQhBaBFYHB6S+QchCEFoEVgcHpL5ByEIQWgRWBwekvkHIQhBWFwE4Nk6//X5rP0jWDuf2nyCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhODpwi+L0nv3jyYIPQwQCoTeOwhB6GGAUCD03kEIQg8DhAKh9w5CEHoYIBQIvXcQgtDDAKFA6L2DEIQeBggFQu8dhCD0MEAoEHrvIAShhwFCgdB7ByEIPQwQCoTeu/cIQg8DhAKh9+49gtDDAKFA6L17jyD0MEAoEHrv3iMIPQwQCoTeu/cIQg8DhAKh9+49gtDDAKFA6L17jzchXB/E9cGtLQ6LeCv/2PleEFqsILSIQQgG3wtCEILQIgYhGHwvCEEIQosYhGAAIQhBCEKLGIRgACEIQQhCixiEYAAh3kAIQosYhGAAoUAIQosYhCAEoUAIQosYhCAEoUAIQosYhCAEoUAIQosYhCAEoUBocVvEIAQhCAVCi9siBiEIQSgQWtwWMQhBCEKB0OIGIQhBCEIQgtDiBiEIQQjCLmwWjUV2aT7Li2/x/N0XCEEoEDofELovEIIQhCB0PiB0XyAEIQhB6HxA6L5ACEIQghCEIHRfIAQhCEEIQhC6LxCCEIQgBCEI3RcIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCgRCEIAQhCEEoEIIQhCAEIQgFQhCCEIQgBKFACEIQghCEIBQIQQhCEIIQhLoMYW1Qag+19vf4R8R+ePO8gRCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQn8PCEEIQhCCEIT+HhCCEIQgBCEI/T0gBCEIQQhCEPp7QAhCEIIQhCD094AQhCAEIQhB6O8BIQhBCEIQgtDfA0IQghCEBh2E/h4QghCEIDToIPT3gBCEIAShQQehvweEIAQhCA06CP09IAQhCEFo0N8L2zpUtfOvLVb/eIEQhCC0OJw/CEEIQhCC0OJw/iAEIQhBCEKLw/mDEIQgBCEILQ4QghCEIAQhCC0OEIIQhCAEIQgtDhCCEIQgBCEILQ4QghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQg7EJYvnj/iFh8ztM/OvYbCEHo4YHQeYLQfgOhQfHwQOg8QQhCEBoUDw+EzhOEIAShQQEhCJ0nCEEIQoMCQhA6TxCCEIQGBYQgdJ4gBCEIDQoIQQhCEIIQhAYFhCAEIQhBCEKDAkIQghCEIAQhCEEIQhCCEIQgFAhBCEIQghCEAiEIQQhCEIJQIAQhCEEIQhAKhCAEIQhBaJEJhCAEIQhBaHFbBMXz1HfvC/wgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEFrcIAQhCEEIQhBa3CAEIQhBaP5BaHGDEIQgBKH5B6HFDUKLAIQgNP8gtLhBaBGAEITmH4QWNwgtAhCC0PyDEIQgtAhACELzD0IQgtAiACEIzT8IQQhCiwCEIDT/IAQhCC0CEILQ/IMQhCC0CEAIQhCqAnNtEVhk5q38jx0IQQhCEILQvIEQhCAEIQhBaN5ACEIQghCEIDRvIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBKBCCEIQgBCEIBUIQghCEIAShQAhCEIIQhCAUCEEIQhCCEIQCIQhBCEIQglAgBCEIQQhCEILE4rA4NmA2z1vzVrsvEFr0zgeE5hmEIAShRe98QGieQQhCEFoczgeE5hmEIAShxeF8QGieQQhCEFoczgeE5hmEIAShxeF8QGieQQhCEFoczgeE5hmEIAShxeF8QGieQQhCEFoczgeE5hmEIAShxeF8QGieQQhCEFoczgeE5hmEIAShxeF8QGieQQhCEFoczgeE5hmEIAShxeF8QGieQQhCEFocIASheQYhCEF4+jLGH14NWhCan0vwg1AgtMhAaH5ACEKBEIQgND8gBKFACEIQmh8QglAgBCEIzQ8IQSgQghCE5geEIBQIQQhC8wNCEAqEIASh+QEhCAVCEILQ/IAQhAIhCEFofkAIQoEQhCA0PyAEoUAIQhCaHxCCUCAEIQjNDwhBKBCCEITmB4QgFAhBCEIQghCEAiEIQQhCEIIQPP/3sC2CrZynyvMGQhCC0OJ2ngIhCEEIQhA6T4EQhBYBCEHoPAVCEFoEIASh8xQIQWgRgBCEzlMgBKFFAEIQOk+BEIQWAQhB6DwFQhBaBCAEofMUCEEIQhCC0HkKhCAEIQhB6DwFQhCCEIQgdJ4CIQhBCEIQOk+BEIQgBCEInadACEIQghCEzlMgBCEIQWgxOU+BEITq/mPhH6Pv/qNj0fvH4iq0IBQIQQhCEIJQAiEIQQhCEEogBCEIQQhCCYQgBCEIQSiBEIQgBCEIJRCCEIQgBKEEQhCCEIQglEAIQhCCEIQSCEFoEYMQhBIIQWgRgxCEEghBaBGDEIQSCEFoEYMQhBIIQWgRgxCEEghBaBGDEIQSCEEIQhCC0CAadIv78nmu/2O0Pm/r8wBCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQWtwgBCEIQQhCEFrcIAQhCEEIQhBa3CAEIQhBCEIQWtwgBCEIQQhCEFrcIAQhCEEIQhBa3CAEIQhBCEIQWtwgBCEIQQhCF29RVu7XPy5b9wtCEFoczgeE7guEIAShxeF8QOi+QAhCEFoczgeE7guEIAShxeF8QAhCEIIQhCB0PiAEIQhBCEIQOh8QghCEIAQhCJ0PCEEIQhCCEITOB4QgBCEIQQhC5wNCEIIQhCAEofMBIQhB6DxBCEKLFYQgBKHzBCEILVYQghCEzhOEILRYQQhCEDpPEILQYgUhCEHoPEEIQosVhCAEofME4Z2H6mFYxGXY1t+X9wtCEIIQhCAEofcLQhCC0P2CEITeLwhBCEL3C0IQer8gBCEI3S8IQej9ghCEHpL7BSEIvV8QgtBDcr8gBKH3C0IQekjuF4Qg9H5BCEIPCYQgBKH3C0KL0kMCIQhB6P2C0KL0kEAIQhB6vyC0KD0kEIIQhN4vCC1KDwmEIASh9wtCi9JDAiEIQej9gtCi9JBACEIQer8gBKGHBEIQgtD7BSEIKw/JIvvu+ay/x9p9+ccIhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEFj0IQQhCEIIQhBY9CEEIQhCCEIQWPQgtVhCCEIQgtOhBaLGCEIQgBKFFD0KLFYQgBCEILXoQWqwg9N5BCEIQOh+LFYTeOwhBCMLK+ax/bw0q++T2fgMhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIS+F4QgBCEIQQhC3wtCEIIQhCAEoe8FIQhBCEIQgtD3gtA+ASEIQQgG3wtC+wSEIAQhGHwvCO0TEIIQhGAAIQjtExCCEIRgACEI7RMQghCEYAAhCO0TEIIQhGAAIQhBaJ5BCEIQghCEIDTPILw8uP5R2GodHjBv/eMFNhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAQhCEEIQhCCEIQgBCEIQQhCELp4EIIQhCAEIQhdPAhBCEIQ2ocgdPEgBCEIQWgfgtDFgxCEIAShfQhCFw9CEIIQhPYhCF08CEEIQhDahyB08SAEIQhBaB+C8M4iri0Cvw9y/xiBEIQeKgj9PghBCEIQeqgg9PsgBCEIQeihgtDvgxCEIAShhwpCvw9CEIIQhB4qCP0+CEEIQhB6qCD0+yAEIQhB6KGCEIQgBCEIQeihghCEIAQhCEHooYIQhCAEIQhB6KGCEIQgBCEIQeihghCEIAQhCEHooYIQhCAEIQhB6KGCEIQgBCEIQQhCEIIQhCAEIQhBCEIQghCEIAShJEkglCQJhJIkgVCSJBBKkgRCSZJAKEkSCCVJAqEkSSCUJAmEkiSBUJIEQkmSQChJEgglSQKhJEkglCQJhJIkgVCSJBBKkgRCSZJAKEkSCCVJAqEkSSCUJAmEkiSBUJIkEEqSBEJJkkAoSRIIJUkCoSRJIJQkCYSSJIFQkiQQSpIEQkmSQChJEgglSQKhJEkglCQJhJIkgVCSJBBKkgRCSZJAKEkSCCVJAqEkSSCUJAmEkiSBUJIkEEqSBEJJkkAoSRIIJUkCoSRJIJQkCYSSJIFQkiQQSpIEQkmSQChJEgglSQKhJAmEkiSBUJIkEEqSBEJJkjL9At++2EgezgKDAAAAAElFTkSuQmCC'
					},
					{
						type:"url",
						width:300,
						height:300,
						left:300,
						top:500,
						data:"https://weiqing.chenyuwulu.top/data/timg.png"
					},
					{
						type:"url",
						width:100,
						height:100,
						left:200,
						top:300,
						data:"https://weiqing.chenyuwulu.top/logo.jpg"
					}
				]
			}
		},
		//计算属性
		computed:{},
		//检测属性
		watch:{},
		onReady() {},
		onShow() {},
		onLoad(options) {
			// #ifdef MP-ALIPAY
				this.src = 'XNDc4NzAwMzk4OA'
			// #endif
			// #ifndef MP-ALIPAY
				this.src = "https://weiqing.chenyuwulu.top/kong.mp3"
			// #endif
			// console.log(this)
		},
		onHide() {},
		methods:{
			return_value(e){
				this.content = e.value
			},
			chufa(){
				this.$refs.daochu.export_image()
			},
			export_loading(){
				uni.showLoading({
					title:"正在导出图片"
				})
			},
			export_success(){
				uni.showToast({
					title:"保存成功",
					icon:"success",
					duration:2000
				})
			}
		}
	}
</script>

<style lang="scss">
	.u-order-title {
		color: #c8c8c8;
		font-weight: bold;
		font-size: 30rpx;
	}
	.u-order-desc {
		margin-top: 20rpx;
		color: #969696;
		font-size: 30rpx;
		.text{
			margin-top: 20rpx;
		}
	}
	.u-order-time {
		margin-top: 20rpx;
		color: #c8c8c8;
		font-size: 26rpx;
	}
</style>
